force-app/main/default/objects/StockX_Sale__c/StockX_Sale__c.object-meta.xml
<CustomObject>
    <description>This object represents a sale on the StockX platform.</description>
    <label>StockX Sale</label>
    <nameField>
        <displayFormat>SXS-{0}</displayFormat>
        <label>StockX Sale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StockX Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StockX_Sale__c/fields/Buyer_Region__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Region__c</fullName>
    <description>The State/Region of the buyer.</description>
    <inlineHelpText>The State/Region of the buyer.</inlineHelpText>
    <label>Buyer Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StockX_Sale__c/fields/Number_of_Days_Listed__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days_Listed__c</fullName>
    <description>The number of days the sneaker was on the market.</description>
    <formula>Order_Date__c -  Release_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The number of days the sneaker was on the market.</inlineHelpText>
    <label>Number of Days Listed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StockX_Sale__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <description>The profit the seller made on the sale.</description>
    <formula>Sale_Price__c -  Retail_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The profit the seller made on the sale.</inlineHelpText>
    <label>Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/StockX_Sale__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <description>The date of the initial sneaker release.</description>
    <inlineHelpText>The date of the initial sneaker release.</inlineHelpText>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/StockX_Sale__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <description>The price the shoe was sold for.</description>
    <inlineHelpText>The price the shoe was sold for.</inlineHelpText>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/StockX_Sale__c/fields/Sneaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Sneaker_Name__c</fullName>
    <description>The name of the sneaker that was sold.</description>
    <inlineHelpText>The name of the sneaker that was sold.</inlineHelpText>
    <label>Sneaker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StockXSalesCardListController.cls
public with sharing class StockXSalesCardListController {
	public StockXSalesCardListController() {}

	@AuraEnabled (cacheable=true)
	public static List<CardWrapper> getSalesData(){
		List<CardWrapper> cardWrappers = new List<CardWrapper>();

		for (StockX_Sale__c sale : [SELECT Name, Sneaker_Name__c, Buyer_Region__c, Number_of_Days_Listed__c, Sale_Price__c, Profit__c, Release_Date__c FROM StockX_Sale__c ORDER BY Profit__c DESC LIMIT 10]) {
			cardWrappers.add(new CardWrapper(sale));
		}

		return cardWrappers;
	}

	@AuraEnabled (cacheable=true)
	public static List<CardWrapper> getSalesDataWithPageSize(Integer numRecordsToLoad){
		List<CardWrapper> cardWrappers = new List<CardWrapper>();

		for (StockX_Sale__c sale : [SELECT Name, Sneaker_Name__c, Buyer_Region__c, Number_of_Days_Listed__c, Sale_Price__c, Profit__c, Release_Date__c FROM StockX_Sale__c ORDER BY Profit__c DESC LIMIT :numRecordsToLoad]) {
			cardWrappers.add(new CardWrapper(sale));
		}

		return cardWrappers;
	}

	@AuraEnabled (cacheable=true)
	public static Map<String, ObjectDescribe> getObjectDescribes() {
		return new Map<String, ObjectDescribe> {
			'stockXSale' => new ObjectDescribe(StockX_Sale__c.sObjectType.getDescribe())
		};
	}

	@AuraEnabled (cacheable=true)
	public static Map<String, FieldDescribe> getFieldDescribes() {
		return new Map<String, FieldDescribe> {
			'saleName' => new FieldDescribe(StockX_Sale__c.Name.getDescribe()),
			'salePrice' => new FieldDescribe(StockX_Sale__c.Sale_Price__c.getDescribe()),
			'sneakerName' => new FieldDescribe(StockX_Sale__c.Sneaker_Name__c.getDescribe()),
			'buyerRegion' => new FieldDescribe(StockX_Sale__c.Buyer_Region__c.getDescribe()),
			'numDaysListed' => new FieldDescribe(StockX_Sale__c.Number_of_Days_Listed__c.getDescribe()),
			'profit' => new FieldDescribe(StockX_Sale__c.Profit__c.getDescribe()),
			'releaseDate' => new FieldDescribe(StockX_Sale__c.Release_Date__c.getDescribe())
		};
	}

	public class ObjectDescribe {
		@AuraEnabled public String label {get;set;}
		@AuraEnabled public String apiName {get;set;}
		@AuraEnabled public Boolean isAccessible {get;set;}
		@AuraEnabled public Boolean isUpdateable {get;set;}

		public ObjectDescribe(Schema.DescribeSObjectResult objDescribe) {
			label =  objDescribe.getLabel();
			apiName = objDescribe.getName();
			isAccessible = objDescribe.isAccessible();
			isUpdateable = objDescribe.isUpdateable();
		}
	}

	public class FieldDescribe {
		@AuraEnabled public String label {get;set;}
		@AuraEnabled public String apiName {get;set;}
		@AuraEnabled public Boolean isAccessible {get;set;}
		@AuraEnabled public Boolean isUpdateable {get;set;}

		public FieldDescribe(Schema.DescribeFieldResult fieldDescribe) {
			label =  fieldDescribe.getLabel();
			apiName = fieldDescribe.getName();
			isAccessible = fieldDescribe.isAccessible();
			isUpdateable = fieldDescribe.isUpdateable();
		}
	}

	public class CardWrapper {

		@AuraEnabled public String saleId {get;set;}
		@AuraEnabled public String buyerRegion {get;set;}
		@AuraEnabled public String numDaysListed {get;set;}
		@AuraEnabled public String profit {get;set;}
		@AuraEnabled public String releaseDate {get;set;}
		@AuraEnabled public String sneakerName  {get;set;}
		@AuraEnabled public String salePrice  {get;set;}

		public CardWrapper() {}

		public CardWrapper(StockX_Sale__c sale) {
			saleId =  sale.Name;
			buyerRegion = sale.Buyer_Region__c;
			numDaysListed = sale.Number_of_Days_Listed__c.format();
			profit = sale.Profit__c.format();
			releaseDate = sale.Release_Date__c.format();
			sneakerName = sale.Sneaker_Name__c;
			salePrice = sale.Sale_Price__c.format();
		}

	}
}